AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: Core Ocean GitHub deployment

Parameters:
  ApplicationId:
    Description: The serverless application id
    Type: String
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubCoreOcean"

Resources:
  Role:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !Ref ApplicationId
        SemanticVersion: 0.0.2
      Parameters:
        GitHubOrg: tiki
        RepositoryName: core-iceberg-catalog
        RoleName: !Ref RoleName

  Policy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - serverlessrepo:*
            Resource: "*"
