AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Ocean GitHub deployment

Parameters:
  RoleName:
    Description: Name of the IAM Role for the deployment
    Type: String
    Default: "GitHubDeployCoreOcean"

Resources:
  Role:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-aws-github-role
        SemanticVersion: 0.0.3
      Parameters:
        GitHubOrg: tiki
        RepositoryName: core-ocean
        RoleName: !Ref RoleName

  Policy:
    Type: AWS::IAM::RolePolicy
    DependsOn: Role
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - serverlessrepo:ListApplicationDependencies
              - serverlessrepo:ListApplicationVersions
              - serverlessrepo:GetApplication
              - serverlessrepo:GetApplicationPolicy
              - serverlessrepo:GetCloudFormationTemplate
            Resource: !Sub "arn:aws:serverlessrepo:*:${AWS::AccountId}:applications/core"
