AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Ocean

Resources:
  Catalog:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-iceberg-catalog
        SemanticVersion: 0.1.7
      Parameters:
        BucketName: mytiki-ocean-test
        DatabaseName: ocean_test
        UtilsName: core-iceberg-utils
        UtilsVersion: 0.2.1

  Metadata:
    Type: AWS::Serverless::Application
    DependsOn: Catalog
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-iceberg-metadata
        SemanticVersion: 0.1.2
      Parameters:
        BucketName: mytiki-ocean-test
        DatabaseName: ocean_test
        UtilsName: core-iceberg-utils
        UtilsVersion: 0.2.1
        QueueName: ocean-metadata

