version = 0.1

[default.global.parameters]
stack_name = "core-ocean-aws"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "core/ocean/aws"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = [
    "CatalogApplicationId=arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-iceberg-catalog",
    "MetadataApplicationId=arn:aws:serverlessrepo:us-east-2:${AWS::AccountId}:applications/core-iceberg-metadata"
]
