AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Description: Core Ocean

Parameters:
  CatalogApplicationId:
    Description: The serverless application id for the catalog
    Type: String
  MetadataApplicationId:
    Description: The serverless application id for the metadata
    Type: String
    Default: "GitHubCoreOcean"

Resources:
  Catalog:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !Ref CatalogApplicationId
        SemanticVersion: 0.1.7
      Parameters:
        BucketName: mytiki-ocean-test
        DatabaseName: ocean_test
        UtilsName: core-iceberg-utils
        UtilsVersion: 0.2.1

  Metadata:
    Type: AWS::Serverless::Application
    DependsOn: Catalog
    Properties:
      Location:
        ApplicationId: !Ref MetadataApplicationId
        SemanticVersion: 0.1.2
      Parameters:
        BucketName: mytiki-ocean-test
        DatabaseName: ocean_test
        UtilsName: core-iceberg-utils
        UtilsVersion: 0.2.1
        QueueName: ocean-metadata

