name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployCoreOcean
          role-session-name: ${{ vars.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: SetVars
        run: |
          sed -i 's/${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/' template.yml

      - name: Validate AWS Template
        run: sam validate --lint

      - name: Build AWS Template
        run: sam build
