name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  UTILS_VERSION: 0.2.1

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployCoreOcean
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SetVars
        run: |
          sed -i 's/\${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/g' infra/github/samconfig.toml
          sed -i 's/\${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/g' infra/aws/samconfig.toml

      - name: Validate AWS Template
        run: cd infra/aws && sam validate --lint

      - name: Build AWS Template
        run: cd infra/aws && sam build

      - name: Validate GitHub Template
        run: cd infra/github && sam validate --lint

      - name: Build GitHub Template
        run: cd infra/github && sam build
