name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  SESSION_NAME: "gh_action"
  AWS_REGION: "us-east-2"

# Cancel any active builds when new commits are pushed
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployCoreOcean
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SetVars
        run: |
          sed -i 's/${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/' infra/github/template.yml
          sed -i 's/${AWS::AccountId}/${{ secrets.AWS_ACCOUNT_ID }}/' infra/aws/template.yml

      - name: Validate AWS Template
        run: cd infra/aws && sam validate --lint

      - name: Build AWS Template
        run: cd infra/aws && sam build

      - name: Validate GitHub Template
        run: cd infra/github && sam validate --lint

      - name: Build GitHub Template
        run: cd infra/github && sam build
